package com.abhishek.Utiles;

public class Constants {

	
	public static String getEmailContentToMe(String pName, String pMsg, String pEmail) {
		return "<div id=':3ja' class='ii gt m14f465204d321312 adP adO'><div id=':3j9' class='a3s' style='overflow: hidden;'><div style='margin:0px'><table cellpadding='0' cellspacing='0' width='700' align='center' border='0' style='font-family:'Open Sans',sans-serif;font-size:12px;margin-top:10px;'><tbody style='background-color:rgba(241,245,247,0.5);vertical-align:top;line-height:20px'><tr><td style='background-color:#ffffff;padding:10px 40px;border:1px solid #c2c2c2;border-radius:7px;'><div style='border-bottom:1px solid #e5e5e5;padding-bottom:5px;margin-bottom:20px'><h6 style='color:#4e5b63;font-size:15px;margin:25px 0px 10px;font-weight:500'>Hi Abhishek,</h6></div><div style='border-bottom:1px solid #e5e5e5;margin-bottom:20px;padding-bottom:15px'><div  style='background-position: left center; margin:5px 2px 2px 2px;display:inline-block'><span style='line-height:25px;width:100%;float:left;margin:0;color:#637374;font-size:15px'>"+pMsg+"</span></div></div><div><dl><dd style='color:#788a95;font-size:15px;margin:0'><strong>"+pName+"</strong></dd><dd style='color:#788a95;font-size:10px;margin:0'>"+pEmail+"</dd></dl></div></td></tr><tr><td colspan='2' style='padding:15px 0px;background-color:#fff'><img src='http://www.abhishek.work/img/logo.png' style='float:left;width:20px;min-height:21px;margin-right:5px' class='CToWUd'><span style='color:rgba(68,87,98,0.69);font-size:13px;float:left;margin-top:3px;line-height:13px'> abhishek.work</span></td></tr></tbody></table><div class='yj6qo'></div><div class='adL'></div></div><div class='adL'></div></div></div>";
	}
	
	
	
	public static String getEmailContent(String pName, String pMsg) {
		return "<div id=':3ja' class='ii gt m14f465204d321312 adP adO'><div id=':3j9' class='a3s' style='overflow: hidden;'><div style='margin:0px'><table cellpadding='0' cellspacing='0' width='700' align='center' border='0' style='font-family:'Open Sans',sans-serif;font-size:12px;margin-top:10px;'><tbody style='background-color:rgba(241,245,247,0.5);vertical-align:top;line-height:20px'><tr><td style='background-color:#ffffff;padding:10px 40px;border:1px solid #c2c2c2;border-radius:7px;'><div style='border-bottom:1px solid #e5e5e5;padding-bottom:5px;margin-bottom:20px'><h6 style='color:#4e5b63;font-size:15px;margin:25px 0px 10px;font-weight:500'>Hi "+pName+",</h6><h6 style='color:#4e5b63;font-size:15px;margin:25px 0px 10px;font-weight:500'>Thankyou for your response,</h6></div><div style='border-bottom:1px solid #e5e5e5;margin-bottom:20px;padding-bottom:15px'><div style='display:inline-block;width:100%'><label style='color:#788a95;width:30%;float:left;font-size:15px'>Your Msg:</label></div><div  style='background-position: left center; margin:5px 2px 2px 2px;display:inline-block'><span style='line-height:25px;width:100%;float:left;margin:0;color:#637374;font-size:15px'>"+pMsg+"</span></div></div><div><dl><dd style='color:#788a95;font-size:15px;margin:0'><strong>Abhishek</strong></dd><dd style='color:#788a95;font-size:10px;margin:0'>abhishek.4133@gmail.com</dd></dl></div></td></tr><tr><td colspan='2' style='padding:15px 0px;background-color:#fff'><img src='http://www.abhishek.work/img/logo.png' style='float:left;width:20px;min-height:21px; margin-right:5px' class='CToWUd'><span style='color:rgba(68,87,98,0.69);font-size:13px;float:left;margin-top:3px;line-height:13px'>  abhishek.work</span></td></tr></tbody></table><div class='yj6qo'></div><div class='adL'></div></div><div class='adL'></div></div></div>";
	}
}